import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import RecipeForm from '@/components/recipes/RecipeForm'

export default async function NewRecipePage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  return (
    <div className="max-w-3xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">New Recipe</h1>
        <p className="text-gray-500 text-sm">Nutritional info will be auto-generated by AI on save</p>
      </div>
      <RecipeForm userId={user.id} />
    </div>
  )
}
